setting_serv: 
  rest:
    rest_port: "8000"
  grpc:
    grpc_port: "12200"
db:
  name: postgres
  # first user - it's name of user for connection
  # second user - it's db name. It is created with this name by default if POSTGRES_DBNAME is not overridden 
  jdbs: postgres://user:pass@localhost:5432/user